### ISSUE TITLE
Aplikasi berjalan lambat saat menyambungkan database yang tepat

### ISSUE THREAD

**Issue by pijarpahlawan** [furaihan/fp-pemrog-lanjut#14]
saya membuat recursive function untuk menemukan connection strings yang tepat. jika terdapat exception, maka block catch akan memanggil recursive function untuk mengiterasi connnection string. keuntungannya, kita gausah merubah kode untuk menemukan connection string yang sesuai. tapi akibatnya aplikasi berjalan lambat ketika mencoba connect. gimana cara optimisasinya?

**Comment by furaihan** [comment]
Cah aneh aneh
